// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWReYZFNUw4W9nH0-OMDb_Rfu0aTJl6iw',
    appId: '1:355241022033:web:7eb8ec44a9e85bcd595e70',
    messagingSenderId: '355241022033',
    projectId: 'flutter-firebase-dersler-1b561',
    authDomain: 'flutter-firebase-dersler-1b561.firebaseapp.com',
    storageBucket: 'flutter-firebase-dersler-1b561.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX_xvEvdvZodLzRommOSvfoaVUUlceRiI',
    appId: '1:355241022033:android:d661dda8bbe4e359595e70',
    messagingSenderId: '355241022033',
    projectId: 'flutter-firebase-dersler-1b561',
    storageBucket: 'flutter-firebase-dersler-1b561.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_rAtVpcEf_Zmob9FFl7RMjTOGq0tamsM',
    appId: '1:355241022033:ios:89ec0a97f2fc82e4595e70',
    messagingSenderId: '355241022033',
    projectId: 'flutter-firebase-dersler-1b561',
    storageBucket: 'flutter-firebase-dersler-1b561.appspot.com',
    iosClientId: '355241022033-40i2od432rb75n7tpg250gib3j54s2ti.apps.googleusercontent.com',
    iosBundleId: 'com.numankaya.flutterFirebaseDersleri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_rAtVpcEf_Zmob9FFl7RMjTOGq0tamsM',
    appId: '1:355241022033:ios:89ec0a97f2fc82e4595e70',
    messagingSenderId: '355241022033',
    projectId: 'flutter-firebase-dersler-1b561',
    storageBucket: 'flutter-firebase-dersler-1b561.appspot.com',
    iosClientId: '355241022033-40i2od432rb75n7tpg250gib3j54s2ti.apps.googleusercontent.com',
    iosBundleId: 'com.numankaya.flutterFirebaseDersleri',
  );
}
